insert into public.events (id, channel, title, title_zh, description, description_zh, event_type, event_type_zh, location, location_zh, starts_at, registration_url)
values
('ai-founder-night-vancouver','luma','AI Founder Night · Vancouver','AI 创始人之夜 · 温哥华','An intimate evening for AI founders, operators and early-stage investors.','面向 AI 创始人、实战专家与早期投资人的深度交流之夜。','Founder Meetup','创始人聚会','Vancouver, BC','加拿大温哥华','2026-09-18T18:30:00-07:00','https://luma.com/'),
('agent-product-salon','luma','Agent Product Salon','AI 智能体产品沙龙','Product builders share what changes when AI moves from answers to actions.','产品建设者共同探讨 AI 从回答问题走向执行任务后的产品变化。','Product Salon','产品沙龙','Burnaby, BC','加拿大本拿比','2026-08-08T14:00:00-07:00','https://luma.com/'),
('global-ai-market-briefing','luma','Global AI Market Briefing','全球 AI 市场简报会','A practical briefing on entering North American markets as an AI startup.','面向 AI 初创公司的北美市场进入实战简报。','Market Briefing','市场简报','Online + Toronto','线上 + 多伦多','2026-07-12T10:00:00-07:00','https://luma.com/'),
('member-ai-market-entry','member','AI Market Entry Lab','AI 全球市场进入实验室','A structured workshop on market selection, customer discovery and your first cross-border pilot.','围绕市场选择、客户探索与首个跨境试点的系统化专业工作坊。','Professional Workshop','专业工作坊','Member Classroom · Online','会员线上教室','2026-10-03T10:00:00-07:00',null),
('member-founder-finance','member','Founder Finance Intensive','创始人融资进阶课','Learn runway planning, investor readiness and the financial story behind a scalable AI company.','学习现金流规划、融资准备，以及可规模化 AI 公司的财务叙事。','Education Series','教育课程','Member Classroom · Online','会员线上教室','2026-09-12T10:00:00-07:00',null),
('member-enterprise-sales','member','Enterprise AI Sales Studio','企业级 AI 销售实战课','Build a credible enterprise offer, pilot structure and stakeholder map with experienced operators.','与实战专家共同打磨企业方案、试点结构与关键决策人地图。','Member Studio','会员实战课','Private Member Session','会员私享活动','2026-08-22T10:00:00-07:00',null)
on conflict (id) do update set title=excluded.title,title_zh=excluded.title_zh,description=excluded.description,description_zh=excluded.description_zh,event_type=excluded.event_type,event_type_zh=excluded.event_type_zh,location=excluded.location,location_zh=excluded.location_zh,starts_at=excluded.starts_at,registration_url=excluded.registration_url,updated_at=now();
