let applyLang=localStorage.getItem('asglobal-language')||'en';
const cfg=window.EVENTS_CONFIG||{};
const getJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},session=getJSON('asglobal-session',null),users=getJSON('asglobal-users',[]),user=users.find(item=>item.email===session?.email),isPaid=user?.membership==='paid';
const applyCopy={en:{home:'← Home',checking:'Checking updates…',checked:'Last checked',updated:'New activity updates',guest:'VIEWING AS GUEST',free:'FREE MEMBER · VIEW ONLY',paid:'GLOBAL+ MEMBER',heroLabel:'EVENT REGISTRATION / TWO PATHS',title:'Choose how you<br><em>want to grow.</em>',intro:'Public community gatherings through Luma, or structured professional learning inside the AI Startup Global member space.',public:'01 / PUBLIC',luma:'Luma events',lumaMethod:'LUMA REGISTRATION',lumaIntro:'Open founder meetups, salons and community conversations. Registration continues on Luma.',member:'02 / MEMBER',learning:'Member learning',siteMethod:'WEBSITE REGISTRATION',memberIntro:'Professional workshops and education programs designed for paid AI Startup Global members.',lock:'Viewable by everyone · Registration requires Global+ membership',view:'View on Luma',register:'Register on website',locked:'Paid members only',registered:'Registered',new:'NEW',center:'Member center →',footer:'Public connection. Professional growth.'},zh:{home:'← 返回首页',checking:'正在检查更新…',checked:'上次检查',updated:'发现新的活动更新',guest:'访客浏览模式',free:'普通用户 · 仅可查看',paid:'GLOBAL+ 付费会员',heroLabel:'活动报名 / 两种路径',title:'选择适合你的<br><em>成长方式。</em>',intro:'通过 Luma 参加公开社区活动，或进入 AI Startup Global 会员空间参加系统化专业课程。',public:'01 / 公开活动',luma:'Luma 活动',lumaMethod:'LUMA 报名',lumaIntro:'开放的创始人聚会、沙龙与社区对谈，点击后前往 Luma 完成报名。',member:'02 / 会员活动',learning:'会员专业课程',siteMethod:'本网站报名',memberIntro:'专为 AI Startup Global 付费会员设计的专业工作坊与教育课程。',lock:'所有人均可查看 · 只有 Global+ 付费会员可以报名',view:'前往 Luma',register:'在本网站报名',locked:'仅限付费会员',registered:'已报名',new:'新活动',center:'会员中心 →',footer:'公开连接，专业成长。'}};
function managedLuma(){return getJSON('asglobal-managed-events',cfg.events||[])}function memberItems(){return getJSON('asglobal-member-events',cfg.memberEvents||[])}const sortNewest=items=>[...items].sort((a,b)=>new Date(b.date)-new Date(a.date));
function eventSignature(){return JSON.stringify({luma:managedLuma().map(x=>[x.id,x.date,x.title]),member:memberItems().map(x=>[x.id,x.date,x.title])})}function checkUpdates(){const now=Date.now(),threeDays=259200000,last=Number(localStorage.getItem('asglobal-events-last-check')||0),previous=localStorage.getItem('asglobal-events-snapshot'),current=eventSignature();
let changed=false;
if(!last||now-last>=threeDays){changed=!!previous&&previous!==current;
localStorage.setItem('asglobal-events-snapshot',current);
localStorage.setItem('asglobal-events-last-check',String(now));
if(changed)localStorage.setItem('asglobal-events-updated','true')}return{last:Number(localStorage.getItem('asglobal-events-last-check')),changed:localStorage.getItem('asglobal-events-updated')==='true'}}function createCard(item,channel,c){const card=document.createElement('article');
card.className='route-event-card';
const date=new Intl.DateTimeFormat(applyLang==='zh-CN'?'zh-CN':'en-CA',{year:'numeric',month:'short',day:'2-digit'}).format(new Date(item.date));
card.innerHTML='<div class="route-event-top"><span>'+channel+'</span><time>'+date+'</time></div><small></small><h3></h3><p></p><div class="route-event-bottom"><span></span></div>';
card.querySelector('small').textContent=applyLang==='zh-CN'?(item.typeZh||item.type):(item.type||'EVENT');
card.querySelector('h3').textContent=applyLang==='zh-CN'?(item.titleZh||item.title):item.title;
card.querySelector('p').textContent=applyLang==='zh-CN'?(item.descriptionZh||item.description):item.description;
card.querySelector('.route-event-bottom span').textContent=applyLang==='zh-CN'?(item.locationZh||item.location):(item.location||'Online');
if(channel==='LUMA'){const link=document.createElement('a');
link.className='btn dark compact';
link.href=item.url||cfg.calendarUrl||'https://luma.com/';
link.target='_blank';
link.rel='noreferrer';
link.textContent=c.view+' ↗';
card.querySelector('.route-event-bottom').append(link)}else{const button=document.createElement('button'),registrations=getJSON('asglobal-member-registrations',[]),registered=registrations.some(x=>x.eventId===item.id&&x.userId===session?.id);
button.className='btn compact '+(isPaid?'dark':'ghost');
button.disabled=!isPaid||registered;
button.textContent=registered?c.registered:(!isPaid?'🔒 '+c.locked:c.register+' →');
button.onclick=()=>{const all=getJSON('asglobal-member-registrations',[]);
all.push({eventId:item.id,userId:session.id,email:session.email,registeredAt:new Date().toISOString()});
localStorage.setItem('asglobal-member-registrations',JSON.stringify(all));
renderApply()};
card.querySelector('.route-event-bottom').append(button)}return card}function renderApply(){const c=applyLang==='zh-CN'?applyCopy.zh:applyCopy.en,update=checkUpdates();
document.documentElement.lang=applyLang;
document.querySelector('[data-apply-lang]').textContent=applyLang==='zh-CN'?'EN':'中文';
document.querySelector('.apply-nav .btn').textContent=c.home;
document.querySelector('.apply-hero>p').textContent=c.heroLabel;
document.querySelector('.apply-hero h1').innerHTML=c.title;
document.querySelector('.apply-hero div p').textContent=c.intro;
document.querySelector('[data-membership-state]').textContent=isPaid?c.paid:(session?c.free:c.guest);
document.querySelector('.luma-route header span').textContent=c.public;
document.querySelector('.luma-route h2').textContent=c.luma;
document.querySelector('.luma-route header>b').textContent=c.lumaMethod;
document.querySelector('.luma-route>p').textContent=c.lumaIntro;
document.querySelector('.member-route header span').textContent=c.member;
document.querySelector('.member-route h2').textContent=c.learning;
document.querySelector('.member-route header>b').textContent=c.siteMethod;
document.querySelector('.member-route>p').textContent=c.memberIntro;
document.querySelector('[data-member-lock-note]').textContent=c.lock;
document.querySelector('.apply-footer p').textContent=c.footer;
document.querySelector('.apply-footer a').textContent=c.center;
const indicator=document.querySelector('[data-update-indicator]');
indicator.textContent=(update.changed?c.updated:c.checked)+' · '+new Intl.DateTimeFormat(applyLang==='zh-CN'?'zh-CN':'en-CA',{month:'short',day:'2-digit'}).format(new Date(update.last));
indicator.classList.toggle('has-update',update.changed);
const lumaRoot=document.querySelector('[data-luma-events]'),memberRoot=document.querySelector('[data-member-events]');
lumaRoot.textContent='';
memberRoot.textContent='';
sortNewest(managedLuma()).forEach(item=>lumaRoot.append(createCard(item,'LUMA',c)));
sortNewest(memberItems()).forEach(item=>memberRoot.append(createCard(item,applyLang==='zh-CN'?'本网站':'WEBSITE',c)))}document.querySelector('[data-apply-lang]').onclick=()=>{applyLang=applyLang==='zh-CN'?'en':'zh-CN';
localStorage.setItem('asglobal-language',applyLang);
renderApply()};
renderApply();
