const projectCopy={
  en:{back:'← AI Radar',footer:'GitHub source data, presented by AI Startup Global.',rank:'DAILY AI RANK',githubOverview:'GITHUB OVERVIEW',visit:'Open on GitHub ↗',homepage:'Project website ↗',today:'Stars today',stars:'Total stars',forks:'Forks',issues:'Open issues',license:'License',about:'What it is.',aboutCopy:'This profile uses the repository description, topics and README excerpt published by the project on GitHub.',readme:'FROM THE README',topics:'PROJECT TOPICS',updated:'Last updated',notFound:'Project not found',notFoundCopy:'This project is not present in today’s AI Top 10.',return:'Return to AI Radar'},
  zh:{back:'← 返回 AI 雷达',footer:'GitHub 公开资料，由 AI Startup Global 整理展示。',rank:'今日 AI 排名',githubOverview:'GITHUB 项目概览',visit:'前往 GitHub ↗',homepage:'项目网站 ↗',today:'今日新增 Stars',stars:'总 Stars',forks:'Forks',issues:'未关闭 Issues',license:'开源许可',about:'它是什么？',aboutCopy:'本页使用项目在 GitHub 发布的仓库简介、主题与 README 摘要，不改写项目的原始含义。',readme:'README 基础介绍',topics:'项目主题',updated:'最后更新',notFound:'未找到项目',notFoundCopy:'这个项目不在今天的 AI Top 10 数据中。',return:'返回 AI 雷达'}
};
let projectLanguage=localStorage.getItem('asglobal-language')==='zh-CN'?'zh':'en';
const projectEscape=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const projectCount=value=>new Intl.NumberFormat(projectLanguage==='zh'?'zh-CN':'en-US',{notation:Number(value)>=10000?'compact':'standard',maximumFractionDigits:1}).format(Number(value)||0);
let currentProject=null;
function applyProjectCopy(){const c=projectCopy[projectLanguage];document.documentElement.lang=projectLanguage==='zh'?'zh-CN':'en';document.querySelector('[data-project-lang]').textContent=projectLanguage==='zh'?'EN':'中文';document.querySelectorAll('[data-copy]').forEach(node=>node.textContent=c[node.dataset.copy]||node.textContent)}
function renderProject(project){
  currentProject=project;const c=projectCopy[projectLanguage],root=document.querySelector('[data-project-root]'),updated=project.updatedAt?new Intl.DateTimeFormat(projectLanguage==='zh'?'zh-CN':'en-CA',{year:'numeric',month:'short',day:'2-digit'}).format(new Date(project.updatedAt)):'—';
  document.title=`${project.repo} — AI Radar`;
  root.innerHTML=`<section class="project-hero"><div class="project-hero-top"><span>${projectEscape(c.rank)} / #${String(project.rank).padStart(2,'0')}</span><span>${projectEscape(project.source)}</span></div><div class="project-owner">${project.avatarUrl?`<img src="${projectEscape(project.avatarUrl)}" alt="">`:''}<span>${projectEscape(project.owner)} / ${projectEscape(project.language||'Open source')}</span></div><h1>${projectEscape(project.name)}</h1><p>${projectEscape(project.description||'No GitHub description is available yet.')}</p><div class="project-actions"><a class="btn white" href="${projectEscape(project.githubUrl)}" target="_blank" rel="noreferrer">${projectEscape(c.visit)}</a>${project.homepage?`<a class="btn ghost" href="${projectEscape(project.homepage)}" target="_blank" rel="noreferrer">${projectEscape(c.homepage)}</a>`:''}</div></section><section class="project-metrics"><div><span>${projectEscape(c.today)}</span><b>+${projectCount(project.starsToday)}</b></div><div><span>${projectEscape(c.stars)}</span><b>${projectCount(project.stars)}</b></div><div><span>${projectEscape(c.forks)}</span><b>${projectCount(project.forks)}</b></div><div><span>${projectEscape(c.issues)}</span><b>${projectCount(project.openIssues)}</b></div><div><span>${projectEscape(c.license)}</span><b>${projectEscape(project.license||'—')}</b></div></section><section class="project-overview"><aside><span>${projectEscape(c.githubOverview)}</span><h2>${projectEscape(c.about)}</h2><p>${projectEscape(c.aboutCopy)}</p><p><b>${projectEscape(c.updated)}:</b> ${projectEscape(updated)}</p></aside><article class="project-readme"><span>${projectEscape(c.readme)}</span><h3>${projectEscape(project.repo)}</h3><p>${projectEscape(project.readmeExcerpt||project.description||'No README excerpt is available.')}</p><div class="project-topics">${(project.topics||[]).slice(0,18).map(topic=>`<span>${projectEscape(topic)}</span>`).join('')}</div></article></section>`;
}
function renderProjectError(){const c=projectCopy[projectLanguage];document.querySelector('[data-project-root]').innerHTML=`<section class="project-error"><h1>${projectEscape(c.notFound)}</h1><p>${projectEscape(c.notFoundCopy)}</p><a class="btn dark" href="ai-radar.html">${projectEscape(c.return)}</a></section>`}
async function loadProject(){
  try{const repo=new URLSearchParams(location.search).get('repo');if(!repo)throw new Error('Missing repo');const response=await fetch(`data/github-trending.json?v=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json(),project=data.projects.find(item=>item.repo.toLowerCase()===repo.toLowerCase());if(!project)throw new Error('Not found');renderProject(project)}catch(error){console.error(error);renderProjectError()}
}
document.querySelector('[data-project-lang]').onclick=()=>{projectLanguage=projectLanguage==='zh'?'en':'zh';localStorage.setItem('asglobal-language',projectLanguage==='zh'?'zh-CN':'en');applyProjectCopy();if(currentProject)renderProject(currentProject)};
document.querySelector('[data-project-year]').textContent=new Date().getFullYear();applyProjectCopy();loadProject();
